# 1. importing pandas

In [2]:
import pandas as pd

# 2. Opening csv file

In [6]:
df=pd.read_csv("aug_test.csv")

In [7]:
df

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours
0,32403,city_41,0.827,Male,Has relevent experience,Full time course,Graduate,STEM,9,<10,NaN,1,21
1,9858,city_103,0.920,Female,Has relevent experience,no_enrollment,Graduate,STEM,5,NaN,Pvt Ltd,1,98
2,31806,city_21,0.624,Male,No relevent experience,no_enrollment,High School,NaN,<1,NaN,Pvt Ltd,never,15
3,27385,city_13,0.827,Male,Has relevent experience,no_enrollment,Masters,STEM,11,10/49,Pvt Ltd,1,39
4,27724,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,10000+,Pvt Ltd,>4,72
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2124,1289,city_103,0.920,Male,No relevent experience,no_enrollment,Graduate,Humanities,16,NaN,Public Sector,4,15
2125,195,city_136,0.897,Male,Has relevent experience,no_enrollment,Masters,STEM,18,NaN,NaN,2,30
2126,31762,city_100,0.887,Male,No relevent experience,no_enrollment,Primary School,NaN,3,NaN,Pvt Ltd,never,18
2127,7873,city_102,0.804,Male,Has relevent experience,Full time course,High School,NaN,7,100-500,Public Sector,1,84
2128,12215,city_102,0.804,Male,Has relevent experience,no_enrollment,Masters,STEM,15,10000+,Pvt Ltd,2,11

# 3. Opening a csv file from an url

In [10]:
import requests
import pandas as pd
from io import StringIO

url = "https://raw.githubusercontent.com/cs109/2014_data/master/countries.csv"

headers = {
    "User-Agent": "Mozilla/5.0"
}

req = requests.get(url, headers=headers)

data = StringIO(req.text)

df = pd.read_csv(data)
df

       Country         Region
0      Algeria         AFRICA
1       Angola         AFRICA
2        Benin         AFRICA
3     Botswana         AFRICA
4      Burkina         AFRICA
..         ...            ...
189   Paraguay  SOUTH AMERICA
190       Peru  SOUTH AMERICA
191   Suriname  SOUTH AMERICA
192    Uruguay  SOUTH AMERICA
193  Venezuela  SOUTH AMERICA

[194 rows x 2 columns]

# TSV FILE

if we have a tsv file then if you open the csv by this code it will give error because tsv files are tab saperated not the comma sapererated.

 
use this code - pd.read_csv("xyz.tsv",sep='\t',names=["x","y","z"])


where x,y,z are the names of the columns

# Header Parameter

suppose you have a file whose 0th index row is the columns name so panda gets confused then u should start your row from 1


pd=df.read_csv("xyz.csv",header=1)

# use_columns

this is used to filter out the columns which one you want .

In [18]:
df.columns

Index(['enrollee_id', 'city', 'city_development_index', 'gender',
       'relevent_experience', 'enrolled_university', 'education_level',
       'major_discipline', 'experience', 'company_size', 'company_type',
       'last_new_job', 'training_hours'],
      dtype='object')

In [20]:
pd.read_csv("aug_test.csv",usecols=['enrollee_id', 'city', 'city_development_index', 'gender'])

      enrollee_id      city  city_development_index  gender
0           32403   city_41                   0.827    Male
1            9858  city_103                   0.920  Female
2           31806   city_21                   0.624    Male
3           27385   city_13                   0.827    Male
4           27724  city_103                   0.920    Male
...           ...       ...                     ...     ...
2124         1289  city_103                   0.920    Male
2125          195  city_136                   0.897    Male
2126        31762  city_100                   0.887    Male
2127         7873  city_102                   0.804    Male
2128        12215  city_102                   0.804    Male

[2129 rows x 4 columns]

# Skiprows

used to skip some rows

In [21]:
pd.read_csv("aug_test.csv",skiprows=[0,1])

,9858,city_103,0.92,Female,Has relevent experience,no_enrollment,Graduate,STEM,5,Unnamed: 9,Pvt Ltd,1,98
0,31806,city_21,0.624,Male,No relevent experience,no_enrollment,High School,NaN,<1,NaN,Pvt Ltd,never,15
1,27385,city_13,0.827,Male,Has relevent experience,no_enrollment,Masters,STEM,11,10/49,Pvt Ltd,1,39
2,27724,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,10000+,Pvt Ltd,>4,72
3,217,city_23,0.899,Male,No relevent experience,Part time course,Masters,STEM,10,NaN,NaN,2,12
4,21465,city_21,0.624,NaN,Has relevent experience,no_enrollment,Graduate,STEM,<1,100-500,Pvt Ltd,1,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2122,1289,city_103,0.920,Male,No relevent experience,no_enrollment,Graduate,Humanities,16,NaN,Public Sector,4,15
2123,195,city_136,0.897,Male,Has relevent experience,no_enrollment,Masters,STEM,18,NaN,NaN,2,30
2124,31762,city_100,0.887,Male,No relevent experience,no_enrollment,Primary School,NaN,3,NaN,Pvt Ltd,never,18
2125,7873,city_102,0.804,Male,Has relevent experience,Full time course,High School,NaN,7,100-500,Public Sector,1,84
2126,12215,city_102,0.804,Male,Has relevent experience,no_enrollment,Masters,STEM,15,10000+,Pvt Ltd,2,11

# Nrows

used to set how many rows you want

In [22]:
pd.read_csv("aug_test.csv",nrows=100)

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours
0,32403,city_41,0.827,Male,Has relevent experience,Full time course,Graduate,STEM,9,<10,NaN,1,21
1,9858,city_103,0.920,Female,Has relevent experience,no_enrollment,Graduate,STEM,5,NaN,Pvt Ltd,1,98
2,31806,city_21,0.624,Male,No relevent experience,no_enrollment,High School,NaN,<1,NaN,Pvt Ltd,never,15
3,27385,city_13,0.827,Male,Has relevent experience,no_enrollment,Masters,STEM,11,10/49,Pvt Ltd,1,39
4,27724,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,10000+,Pvt Ltd,>4,72
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2934,city_75,0.939,Male,Has relevent experience,no_enrollment,Phd,STEM,>20,1000-4999,Pvt Ltd,3,328
96,12919,city_103,0.920,Female,Has relevent experience,no_enrollment,Graduate,Humanities,4,NaN,NaN,1,47
97,4386,city_21,0.624,Male,No relevent experience,Full time course,High School,NaN,3,<10,Early Stage Startup,2,36
98,22462,city_21,0.624,NaN,Has relevent experience,no_enrollment,Graduate,STEM,9,10000+,NGO,1,30
99,13988,city_103,0.920,NaN,Has relevent experience,Part time course,Masters,STEM,16,10000+,Pvt Ltd,>4,36

# Encoading Parameters

generally we have datasets whose encoading parameter is UTF 8 but some of them are different and when you want to open them you get an error , by this way you can handle them

pd.read_csv("xvy.csv",encoading=" bnmvn (encoading type)")

# Skip bad lines

use to lines whose data is behaving differentlly in any way .

pd.read_csv("aug_test.csv",error_bad_lines=False)

# Dtypes Parameters
it is used to change the datatypes of the column.
ex-from int to float , or vice versa

pd.read_csv("aug_test.csv",dtypes={'target':int})  from float to int

# Handling dates
In the given csv files date's datatype is string so you can not fetch its year ,month or anything , to overcome this we use this

pd.read_csv("aug_test.csv",parse_dates=["date"])

# Convertors
This feature is used where suppose you have a column and it contains very long name and you want short name for them then you can use convertors.

pd.read_csv("aug_test.csv",convertors={"column name":function name})

# na_values parameters
This is used for missing values sometimes in the place of missing values there would be placeholders like (-,%,;) so we can use na_values it convers all these into the NaN .

pd.read_csv("aug_test.csv",na_values=['-','%'])

# Loading a huge dataset in chunks
If you are working with large dataset so working with large dataset would be difficult to divide it into the chunks and apply operations in loops

pd.read_csv("aug_test.csv",chunksize=5000)